### ISSUE TITLE
the problem with the rollout speed

### ISSUE THREAD

**Issue by asilverlight** [Agent-RL/ReSearch#3]
I look at the original code, which deduces serially for each rollout, that is, data is generated one by one. 
When I was doing the training, I found that the GPU utility(UTL) was very low, only 20-30%.
Then I changed it to parallel reasoning by myself, that is, all the data in a batch is first inference in parallel, and then the sequences that need to be searched are searched, and then the subsequent inference is performed on those sequences.
However, I found that GPU usage was still very low, and even when the memory usage(MEM) reached 60%, the utility(UTL) was only about 10%.
I think my slow training speed may be caused by the low GPU utility. May I ask whether the GPU utility rate can be improved by adjusting config in this code, or whether the low GPU utility is normal and the model training process is really slow?:-)
My own configuration is as follows:
```
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1
export VLLM_ATTENTION_BACKEND=XFORMERS

PROMPT_KEY=question
TRAIN_BATCH_SIZE=4
PPO_MINI_BATCH_SIZE=64
MAX_PROMPT_LENGTH=512
MAX_RESPONSE_LENGTH=4096
APPLY_CHAT=False
PROMPT_TEMPLATE_NAME=qa_template
ACTOR_MODEL_PATH=/home/path/Reasoning/model/stage3/qwen2.5-3b-instruct/global_step_41/actor/huggingface  # your model path here
REWARD_MANAGER=qa
ROLLOUT_N=5
SEARCH_URL=http://0.0.0.0:1557  # your host search url here
PROJECT_NAME=grpo_qa_ir
EXPERIMENT_NAME=qwen2_5_3b_grpo_ir_stage2
NNODES=1
SAVE_FREQ=150
TEST_FREQ=10
TOTAL_EPOCHS=1
WANDB_API_KEY=xxx
SAVE_PATH=/home/path/Reasoning/model/stage2/qwen2.5-3b-instruct  # your save path here
export CUDA_VISIBLE_DEVICES=0,1

TRAIN_DATA_PATH=/home/path/Reasoning/processed_data/r1-search-stage2/train.parquet  # your train data path here
DEV_DATA_PATH=/home/path/Reasoning/processed_data/r1-search-stage2/test.parquet  # your dev data path here

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prompt_key) PROMPT_KEY="$2"; shift 2;;
        --train_batch_size) TRAIN_BATCH_SIZE="$2"; shift 2;;
        --ppo_mini_batch_size) PPO_MINI_BATCH_SIZE="$2"; shift 2;;
        --max_prompt_length) MAX_PROMPT_LENGTH="$2"; shift 2;;
        --max_response_length) MAX_RESPONSE_LENGTH="$2"; shift 2;;
        --apply_chat) APPLY_CHAT="$2"; shift 2;;
        --prompt_template_name) PROMPT_TEMPLATE_NAME="$2"; shift 2;;
        --actor_model_path) ACTOR_MODEL_PATH="$2"; shift 2;;
        --reward_manager) REWARD_MANAGER="$2"; shift 2;;
        --rollout_n) ROLLOUT_N="$2"; shift 2;;
        --search_url) SEARCH_URL="$2"; shift 2;;
        --project_name) PROJECT_NAME="$2"; shift 2;;
        --experiment_name) EXPERIMENT_NAME="$2"; shift 2;;
        --nnodes) NNODES="$2"; shift 2;;
        --save_freq) SAVE_FREQ="$2"; shift 2;;
        --test_freq) TEST_FREQ="$2"; shift 2;;
        --total_epochs) TOTAL_EPOCHS="$2"; shift 2;;
        --wandb_api_key) WANDB_API_KEY="$2"; shift 2;;
        --save_path) SAVE_PATH="$2"; shift 2;;
        --train_data_path) TRAIN_DATA_PATH="$2"; shift 2;;
        --dev_data_path) DEV_DATA_PATH="$2"; shift 2;;
        *)
            echo "Error: unknown argument '$1'" >&2
            exit 1;;
    esac
done

if [ "$WANDB_API_KEY" != "None" ]; then
    wandb login --relogin $WANDB_API_KEY
fi

# make output directory
if [ ! -d "$SAVE_PATH" ]; then
    mkdir -p $SAVE_PATH
fi
set -x
train_files=$TRAIN_DATA_PATH
test_files=$DEV_DATA_PATH
export PYTHONPATH=/home/path/ReSearch-main/verl:$PYTHONPATH
    # algorithm.adv_estimator=reinforce_plus_plus \
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    algorithm.kl_ctrl.kl_coef=0.001 \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.prompt_key=${PROMPT_KEY} \
    data.train_batch_size=${TRAIN_BATCH_SIZE} \
    data.max_prompt_length=${MAX_PROMPT_LENGTH} \
    data.max_response_length=${MAX_RESPONSE_LENGTH} \
    data.apply_chat=${APPLY_CHAT} \
    data.prompt_template_name=${PROMPT_TEMPLATE_NAME} \
    actor_rollout_ref.model.path=${ACTOR_MODEL_PATH} \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=${PPO_MINI_BATCH_SIZE} \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=$((2*(MAX_PROMPT_LENGTH+MAX_RESPONSE_LENGTH))) \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.batch_retrieval=True \ # I added this parameter to determine whether the rollout mode is parallel or serial
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.grad_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=$((4*(MAX_PROMPT_LENGTH+MAX_RESPONSE_LENGTH))) \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm_with_search \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.n=${ROLLOUT_N} \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=$((4*(MAX_PROMPT_LENGTH+MAX_RESPONSE_LENGTH))) \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.reward_manager=${REWARD_MANAGER} \
    trainer.critic_warmup=0 \
    trainer.logger="[console, wandb]" \
    trainer.project_name=${PROJECT_NAME} \
    trainer.experiment_name=${EXPERIMENT_NAME} \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=${NNODES} \
    trainer.save_freq=${SAVE_FREQ} \
    trainer.test_freq=${TEST_FREQ} \
    trainer.total_epochs=${TOTAL_EPOCHS} \
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir=${SAVE_PATH} \
    trainer.print=True \
    trainer.resume_from_path=True \
    hydra.run.dir=${SAVE_PATH}/outputs \
    +trainer.val_before_train=True \
    +actor_rollout_ref.rollout.search_url=${SEARCH_URL} \
    +data.save_path=${SAVE_PATH}/rollout_result.jsonl | tee $SAVE_PATH/run.log
```
The parallel code I modified myself is as follows
```
@torch.no_grad()
    def generate_sequences_v2(self, prompts: DataProto, **kwargs) -> DataProto:
        """
        为GRPO训练并行生成多个响应，支持中间检索的并行处理。
        
        Args:
            prompts (DataProto): 输入数据，包含 input_ids, attention_mask 等。
            **kwargs: 采样参数的额外配置。
        
        Returns:
            DataProto: 包含生成的响应和其他元数据的输出。
        """
        # 初始化缓存引擎
        if self.config.free_cache_engine:
            self.inference_engine.init_cache_engine()

        # 提取输入数据
        idx = prompts.batch['input_ids']  # (bs, prompt_length)
        attention_mask = prompts.batch['attention_mask']
        position_ids = prompts.batch['position_ids']
        eos_token_id = prompts.meta_info['eos_token_id']
        batch_size = idx.size(0)
        
        # 获取采样参数
        do_sample = prompts.meta_info.get('do_sample', True)
        n_responses = self.config.n if do_sample else 1
        
        if not do_sample:
            kwargs = {
                'best_of': 1,
                'top_p': 1.0,
                'top_k': -1,
                'min_p': 0.0,
                'temperature': 0,
                'n': 1  # if greedy, only 1 response
            }

        # 将输入转换为 List[List[int]] 格式
        idx_list = [_pre_process_inputs(self.pad_token_id, idx[i]) for i in range(batch_size)]
        
        # 扩展样本
        total_samples = batch_size * n_responses
        generating = list(range(total_samples))  # 正在生成的样本索引
        # 所有样本，假如batch=2，n=5，那么completed=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        completed = []  # 已完成的样本索引
        
        # 记录每个扩展样本的原始索引和响应编号
        sample_mapping = [(i // n_responses, i % n_responses) for i in range(total_samples)]
        # 第一个编号代表对于batch中的哪一个样本，第二个编号代表对于batch中该样本的哪一个响应
        
        # 初始化上下文
        contexts = [idx_list[i // n_responses].copy() for i in range(total_samples)]
        result_masks = [[] for _ in range(total_samples)]  # 用于存储每个样本的mask
        search_rounds = [0 for _ in range(total_samples)]  # 记录每个样本的检索轮数
        
        # 为每个样本初始化最大生成token数
        curr_max_tokens_list = [self.sampling_params.max_tokens] * total_samples
        
        # 主生成循环
        with self.update_sampling_params(**kwargs):
            # 初始化进度条
            pbar = tqdm(total=len(generating), desc="处理进度") if self.config.use_tqdm else None
            
            while generating:
                input_ids_list = [contexts[i] for i in generating]
                
                # 为每个生成样本设置对应的max_tokens限制
                # 形如 {sample_idx: remaining_tokens, ...}
                current_max_tokens = {idx_: curr_max_tokens_list[idx_] for idx_ in generating}
                
                # 检查是否所有序列都已达到最大生成长度
                # 如果所有序列的剩余可生成token数都为0或负数，则结束生成
                if all(tokens <= 0 for idx_, tokens in current_max_tokens.items()):
                    break
                
                # 使用vLLM模型生成下一段文本
                with self.update_sampling_params(n=1, stop=['</search>'], max_tokens=self.config.max_num_seqs, detokenize=True):
                    outputs = self.inference_engine.generate(
                        prompts=None,
                        sampling_params=self.sampling_params,
                        prompt_token_ids=input_ids_list,
                        use_tqdm=False,
                    )
                
                # 处理每个样本的生成结果
                newly_completed = []  # 记录本轮完成生成的样本索引
                
                # 用于存储生成结果中不同类型序列的索引
                search_indices = [] # 存储需要进行检索的序列的索引和内容(即以</search>结尾的序列)
                other_indices = []  # 存储其他普通序列的索引和内容
                outputs = outputs[0]
                
                for i, (idx_, output) in enumerate(zip(generating, outputs)):
                    generated_ids = output.tolist()
                    generated_ids = [token for token in generated_ids if token != self.tokenizer.pad_token_id and token != self.tokenizer.eos_token_id]
                    output_str = self.tokenizer.decode(generated_ids)
                    
                    # 如果已经超过三轮检索，直接完成生成
                    if search_rounds[idx_] >= 3:
                        other_indices.append((i, idx_, generated_ids))
                        continue
                        
                    if output_str.strip().endswith('</search>'):
                        search_indices.append((i, idx_, generated_ids, output_str))
                    else:
                        other_indices.append((i, idx_, generated_ids))
                
                # 并行处理需要检索的序列
                if search_indices:
                    search_contents = []
                    for _, _, _, output_str in search_indices:
                        search_content = self.extract_search_content(output_str)
                        search_contents.append(search_content)
                    search_results = []
                    try:
                        # search_results = self.batch_search(search_contents)
                        for search_content in search_contents:
                            search_result = self.search(search_content)
                            search_results.append(search_result)
                    except Exception as e:
                        search_results = ["search failed"] * len(search_contents)
                        print(f"search failed: {e}")
                    
                    for (i, idx_, generated_ids, output_str), search_result in zip(search_indices, search_results):
                        search_rounds[idx_] += 1
                        prefix_len = len(generated_ids)
                        new_output_ids = self.tokenizer.encode(f"{output_str} <result>\n{search_result}\n</result>")
                        
                        new_output_ids = new_output_ids[:curr_max_tokens_list[idx_]]
                        contexts[idx_] += new_output_ids
                        # 为生成的内容添加mask(1)，为检索内容添加mask(0)
                        result_masks[idx_].extend([1] * prefix_len)  # 生成部分
                        result_masks[idx_].extend([0] * (len(new_output_ids) - prefix_len))  # 检索部分
                        curr_max_tokens_list[idx_] -= len(new_output_ids)
                
                # 处理其他序列
                # 这里的其他序列是指没有生成EOS token的序列
                for i, idx_, generated_ids in other_indices:
                    contexts[idx_] += generated_ids
                    # 为生成的内容添加mask(1)
                    result_masks[idx_].extend([1] * len(generated_ids))
                    curr_max_tokens_list[idx_] -= len(generated_ids)
                    newly_completed.append(idx_)
                    if pbar:
                        pbar.update(1)
                
                # 将本轮完成的样本添加到completed列表中
                completed.extend(newly_completed)
                
                # 更新generating列表，移除已完成的样本
                generating = [i for i in generating if i not in completed]
            
            # 关闭进度条
            if pbar:
                pbar.close()
```

**Comment by yaxundai** [comment]
I also encountered the same problem, the training is too slow

**Comment by AnselCmy** [comment]
Thanks for sharing your observations and experiments! 

1. You're absolutely right that the current rollout implementation can be optimized. We've actually developed an improved version of parallel rollout generation. This optimized version is currently undergoing final validation and will be open-sourced later this week. Stay tuned!
2. The low GPU utility during training could stem from multiple factors, for example, imbalanced rollout across distributed nodes. This is indeed an active research challenge in RL-based training. We welcome community discussion about potential solutions.
3. For the training speed, could you share your cluster configuration? From our experience, on ​8×8 H800 nodes training a 7B model, with batch_size=256, per-step time ranges 5-10 minutes.

**Comment by asilverlight** [comment]
> Thanks for sharing your observations and experiments!
> 
> 1. You're absolutely right that the current rollout implementation can be optimized. We've actually developed an improved version of parallel rollout generation. This optimized version is currently undergoing final validation and will be open-sourced later this week. Stay tuned!
> 2. The low GPU utility during training could stem from multiple factors, for example, imbalanced rollout across distributed nodes. This is indeed an active research challenge in RL-based training. We welcome community discussion about potential solutions.
> 3. For the training speed, could you share your cluster configuration? From our experience, on ​8×8 H800 nodes training a 7B model, with batch_size=256, per-step time ranges 5-10 minutes.

Thanks for your reply! In my experiment, I used 1*2 A800, 80G per GPU, and I trained a 3B instruct model, with batch_size=4, per-step time ranges 5-8 minutes. However, since I am running with my parallel inference code, I set rollout_n=5, so each time the model needs to infer 20 sequences in parallel

**Comment by AnselCmy** [comment]
Hi @asilverlight @yaxundai, we have released a new implementation, with more efficient rollout process, please check it out!

**Comment by LePanda026** [comment]
In fact that, the slow speed maybe attributed to the rollout parameters of vLLM, if you set the detokenize to True, the rollout speed will be slower than False, this issue also is proposed in veRL repo. You can reference here: https://github.com/volcengine/verl/issues/238

**Comment by AnselCmy** [comment]
Hi, thanks @LePanda026. It seems that using `detokenize` is affecting the rollout speed, and we'll consider fixing that!

**Comment by zihaolucky** [comment]
set `detokenize=False` still very slow. 

```
(WorkerDict pid=168716) INFO 04-10 05:24:39 metrics.py:349] Avg prompt throughput: 591.2 tokens/s, Avg generation throughput: 4.3 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 62 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%.
(WorkerDict pid=168580) INFO 04-10 05:24:39 metrics.py:349] Avg prompt throughput: 558.2 tokens/s, Avg generation throughput: 16.2 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 62 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%.
(WorkerDict pid=168580) INFO 04-10 05:24:44 metrics.py:349] Avg prompt throughput: 2391.3 tokens/s, Avg generation throughput: 31.0 tokens/s, Running: 71 reqs, Swapped: 0 reqs, Pending: 9 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%.
(WorkerDict pid=168716) INFO 04-10 05:24:44 metrics.py:349] Avg prompt throughput: 2254.6 tokens/s, Avg generation throughput: 29.2 tokens/s, Running: 71 reqs, Swapped: 0 reqs, Pending: 9 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%.
(WorkerDict pid=168716) INFO 04-10 05:24:49 metrics.py:349] Avg prompt throughput: 378.5 tokens/s, Avg generation throughput: 29.0 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.8%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
(WorkerDict pid=168716) INFO 04-10 05:24:55 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.8 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
(WorkerDict pid=168716) INFO 04-10 05:25:01 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.1 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
(WorkerDict pid=168716) INFO 04-10 05:25:07 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.0 tokens/s, Running: 79 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
(WorkerDict pid=168716) INFO 04-10 05:25:12 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.6 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
(WorkerDict pid=168716) INFO 04-10 05:25:18 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.4 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
(WorkerDict pid=168716) INFO 04-10 05:25:24 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.4 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
```

**Comment by LePanda026** [comment]
> set `detokenize=False` still very slow.
> 
> ```
> (WorkerDict pid=168716) INFO 04-10 05:24:39 metrics.py:349] Avg prompt throughput: 591.2 tokens/s, Avg generation throughput: 4.3 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 62 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%.
> (WorkerDict pid=168580) INFO 04-10 05:24:39 metrics.py:349] Avg prompt throughput: 558.2 tokens/s, Avg generation throughput: 16.2 tokens/s, Running: 18 reqs, Swapped: 0 reqs, Pending: 62 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%.
> (WorkerDict pid=168580) INFO 04-10 05:24:44 metrics.py:349] Avg prompt throughput: 2391.3 tokens/s, Avg generation throughput: 31.0 tokens/s, Running: 71 reqs, Swapped: 0 reqs, Pending: 9 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%.
> (WorkerDict pid=168716) INFO 04-10 05:24:44 metrics.py:349] Avg prompt throughput: 2254.6 tokens/s, Avg generation throughput: 29.2 tokens/s, Running: 71 reqs, Swapped: 0 reqs, Pending: 9 reqs, GPU KV cache usage: 5.2%, CPU KV cache usage: 0.0%.
> (WorkerDict pid=168716) INFO 04-10 05:24:49 metrics.py:349] Avg prompt throughput: 378.5 tokens/s, Avg generation throughput: 29.0 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.8%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
> (WorkerDict pid=168716) INFO 04-10 05:24:55 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.8 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
> (WorkerDict pid=168716) INFO 04-10 05:25:01 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.1 tokens/s, Running: 80 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
> (WorkerDict pid=168716) INFO 04-10 05:25:07 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.0 tokens/s, Running: 79 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
> (WorkerDict pid=168716) INFO 04-10 05:25:12 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.6 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
> (WorkerDict pid=168716) INFO 04-10 05:25:18 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.4 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.9%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
> (WorkerDict pid=168716) INFO 04-10 05:25:24 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.4 tokens/s, Running: 78 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.0%, CPU KV cache usage: 0.0%. [repeated 2x across cluster]
> ```

Have you set detokenize=False globally? Due to the update_params function within the context, after generation, detokenize will be reset to default value. If there is still a speed issue, I'm not sure what could be causing it—sorry!

**Comment by zihaolucky** [comment]
@LePanda026 has been set to False, does this part has to be set True?

```
 # generate in batch, according to active max tokens
                with self.update_sampling_params(n=1, stop=['</search>'], max_tokens=max(active_max_tokens), detokenize=True):
                    outputs = self.inference_engine.generate(
                        prompts=None,
                        sampling_params=self.sampling_params,
                        prompt_token_ids=active_inputs,
                        use_tqdm=False
                    )
```

**Comment by LePanda026** [comment]
> [@LePanda026](https://github.com/LePanda026) has been set to False, does this part has to be set True?
> 
> ```
>  # generate in batch, according to active max tokens
>                 with self.update_sampling_params(n=1, stop=['</search>'], max_tokens=max(active_max_tokens), detokenize=True):
>                     outputs = self.inference_engine.generate(
>                         prompts=None,
>                         sampling_params=self.sampling_params,
>                         prompt_token_ids=active_inputs,
>                         use_tqdm=False
>                     )
> ```

In the code you provided, you also need to set it to False. However, if you set this to False, you must wait until the entire sequence is generated.

I didn’t use the code from this repository directly, but I encountered the same issue. Unlike this repository, my implementation waits for the entire sentence to be generated before parsing special strings like <search>, <func_call>, etc. Generating the full sequence is slower, but you can limit the sequence length in each generation step to mitigate this.

There’s another potential issue you may need to check:
![Image](https://github.com/user-attachments/assets/65789b06-71e3-4294-a122-67b84a41589b)

Finally, there may be other factors causing the slowdown, what i can do for you is provide my eaxperience. Sorry.

**Comment by AnselCmy** [comment]
Hi @zihaolucky, thank you for raising this issue, and thanks to @LePanda026 for the helpful explanation.  

It's correct that setting `detokenize=True` does slow down the vLLM output, and this issue seems to originate from verl itself (as this issue [here](https://github.com/volcengine/verl/issues/238)). In the current version of our code, we use `</search>` as a stop condition (as shown in this [line](https://github.com/Agent-RL/ReSearch/blob/9aba086d571a1cba44f374cefebb5e12478daab9/src/verl/workers/rollout/vllm_rollout/vllm_rollout.py#L357)). However, setting `detokenize=True` is necessary when using a string as a stop condition, which introduces an inherent limitation in this version. As a result, if you set `detokenize=True`, you cannot use `</search>` as the stop condition and must wait for the entire sequence to be generated before stopping, which is less efficient (@LePanda026 also mentioned this).

In the next version, we plan to address this by using a different format, such as using `<|im_end|>` to mark the end of a search invocation. Using a single token like this is safe even when `detokenize=False`. Additionally, it appears that in the latest version of verl (likely > v0.3), `detokenize=True` no longer significantly impacts inference speed, though I haven’t personally verified this through testing.  

If anyone has further suggestions, insights, or experience with this issue, please share them here. We’re happy to discuss and explore better solutions together!

**Comment by zihaolucky** [comment]
I asked a member of verl team and he said the open-sourced version doesn't support vllm serving in standalone worker. 

1. I think it would be much faster if we can host rollout worker in that way(by extending the rollout worker num, the generation time will be much faster), but the parameter update become an problem :(
2. we have to wait until all inputs are generated as a batch inputs might contains various length in output. shall we use yield mode? (release rollout worker resource to handle next batch and return the finished ones)

**Comment by AnselCmy** [comment]
> I asked a member of verl team and he said the open-sourced version doesn't support vllm serving in standalone worker.
> 
> 1. I think it would be much faster if we can host rollout worker in that way(by extending the rollout worker num, the generation time will be much faster), but the parameter update become an problem :(
> 2. we have to wait until all inputs are generated as a batch inputs might contains various length in output. shall we use yield mode? (release rollout worker resource to handle next batch and return the finished ones)

Thanks @zihaolucky for your suggestions. Let me clarify a few points:

1. Regarding the standalone rollout worker suggestion: As previously mentioned, the rollout speed issue primarily stems from `detokenize=true`. Hosting standalone rollout workers wouldn't fundamentally address this issue, and it would significantly deviate from verl's core design principles.

2. Concerning the yield mode suggestion: Currently, VERL doesn't support this type of generation where partial results are returned while processing continues.

We are well aware that generation speed is a critical concern. I'm happy to share that we are actively developing the next version of this work, which will include significant performance improvements. We expect to release a more efficient version in the coming weeks. Stay tuned for updates!

**Comment by AnselCmy** [comment]
Hi @zihaolucky @asilverlight @LePanda026 @yaxundai,

Our code has been updated. In this version, we've solved the rollout speed problem. Currently, the model output is terminated by the `<|im_end|>` token rather than a string, so there's no need to set `detokenize=True`.

Furthermore, we've also updated to verl 0.3.0 and vLLM 0.8.4. We've observed that setting `detokenize=True` doesn't affect the speed, although we're not using this parameter in the current version.

**Comment by qishenghu** [comment]
> Hi [@zihaolucky](https://github.com/zihaolucky) [@asilverlight](https://github.com/asilverlight) [@LePanda026](https://github.com/LePanda026) [@yaxundai](https://github.com/yaxundai),
> 
> Our code has been updated. In this version, we've solved the rollout speed problem. Currently, the model output is terminated by the `<|im_end|>` token rather than a string, so there's no need to set `detokenize=True`.
> 
> Furthermore, we've also updated to verl 0.3.0 and vLLM 0.8.4. We've observed that setting `detokenize=True` doesn't affect the speed, although we're not using this parameter in the current version.

Dear author,

Thank you for the great work. I would like to ask if using the the last version of 'ReSearch' and simply update the vllm to 0.8.4 can solve the rollout speed issue in that branch?

Thanks!

**Comment by LePanda026** [comment]
Amazing!



发自我的iPhone


------------------ Original ------------------
From: qshu ***@***.***&gt;
Date: Sat,Apr 26,2025 4:51 PM
To: Agent-RL/ReCall ***@***.***&gt;
Cc: LePanda026 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Agent-RL/ReCall] the problem with the rollout speed (Issue #3)

**Comment by JunzheShen** [comment]
> Hi [@zihaolucky](https://github.com/zihaolucky) [@asilverlight](https://github.com/asilverlight) [@LePanda026](https://github.com/LePanda026) [@yaxundai](https://github.com/yaxundai),
> 
> Our code has been updated. In this version, we've solved the rollout speed problem. Currently, the model output is terminated by the `<|im_end|>` token rather than a string, so there's no need to set `detokenize=True`.
> 
> Furthermore, we've also updated to verl 0.3.0 and vLLM 0.8.4. We've observed that setting `detokenize=True` doesn't affect the speed, although we're not using this parameter in the current version.

Thank you for your effort! However I find the code confusing: I think to terminate the generation once the model outputs `<|im_end|>`, this token should appear in the prompt to guide the model. But in the prompt template, there's no `<|im_end|>` token, only <tool_call> .

**Comment by AnselCmy** [comment]
> > Hi [@zihaolucky](https://github.com/zihaolucky) [@asilverlight](https://github.com/asilverlight) [@LePanda026](https://github.com/LePanda026) [@yaxundai](https://github.com/yaxundai),
> > Our code has been updated. In this version, we've solved the rollout speed problem. Currently, the model output is terminated by the `<|im_end|>` token rather than a string, so there's no need to set `detokenize=True`.
> > Furthermore, we've also updated to verl 0.3.0 and vLLM 0.8.4. We've observed that setting `detokenize=True` doesn't affect the speed, although we're not using this parameter in the current version.
> 
> Dear author [@AnselCmy](https://github.com/AnselCmy) ,
> 
> Thank you for the great work. I would like to ask if using the the last version of 'ReSearch' and simply update the vllm to 0.8.4 can solve the rollout speed issue in that branch?
> 
> Thanks

You cannot simply update vLLM to 0.8.4 in the `ReSearch` implementation. To properly fix the rollout speed issue in the old implementation in `re-search` branch, you need to: update vLLM to 0.8.4, update verl to 0.3.0, then move the vLLMRolloutWithSearch implementation to vllm_rollout_spmd. These migration steps essentially align with what we're currently doing in ReCall. The ReCall implementation is also compatible with search functionality, but instead of using `<search>` markers, it uses `<tool_call>`, and treat search as a tool. We recommend using the latest ReCall implementation. However, if you specifically want to migrate ReSearch, feel free to ask any questions during the process, and I'll be happy to help.

**Comment by AnselCmy** [comment]
> > Hi [@zihaolucky](https://github.com/zihaolucky) [@asilverlight](https://github.com/asilverlight) [@LePanda026](https://github.com/LePanda026) [@yaxundai](https://github.com/yaxundai),
> > Our code has been updated. In this version, we've solved the rollout speed problem. Currently, the model output is terminated by the `<|im_end|>` token rather than a string, so there's no need to set `detokenize=True`.
> > Furthermore, we've also updated to verl 0.3.0 and vLLM 0.8.4. We've observed that setting `detokenize=True` doesn't affect the speed, although we're not using this parameter in the current version.
> 
> Thank you for your effort! However I find the code confusing: I think to terminate the generation once the model outputs `<|im_end|>`, this token should appear in the prompt to guide the model. But in the prompt template, there's no `<|im_end|>` token, only <tool_call> .

In the current version of ReCall, we utilize instruct-tuned models (Qwen2.5-7B-Instruct and Qwen2.5-32B-Instruct). The ability to use `<|im_end|>` as an end token is a feature provided by these instruct-tuned models.
